### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by Pro-Z-Emil** [mikabytes/gearbox#11]
Using configuration file at C:\Users\pro-z\config.mjs
Gearbox started on http://localhost:2112
node:internal/fs/watchers:247
    const error = new UVException({
                  ^

Error: EPERM: operation not permitted, watch 'C:\Users\pro-z\Cookies'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2464:36)
    at createFsWatchInstance (C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\node_modules\chokidar\lib\nodefs-handler.js:567:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\node_modules\chokidar\lib\nodefs-handler.js:617:16)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\node_modules\chokidar\index.js:647:10)
    at NodeFsHandler._addToNodeFs (C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\node_modules\chokidar\lib\nodefs-handler.js:645:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\pro-z\\Cookies',
  filename: 'C:\\Users\\pro-z\\Cookies'
}

Node.js v20.12.0

**Comment by mikabytes** [comment]
Thanks for reporting this. This happens due to Hotserve being run even if it wasn't in active development. v0.7.2 should fix that issue @Pro-Z-Emil please let me know.

**Comment by Pro-Z-Emil** [comment]
It seems to be fixed.

**Comment by mikabytes** [comment]
Closing this as he told me elsewhere that it works now.
