### ISSUE TITLE
Can't start on windows

### ISSUE THREAD

**Issue by Pro-Z-Emil** [mikabytes/gearbox#9]
```
node:internal/modules/esm/resolve:782
    throw new ERR_INVALID_MODULE_SPECIFIER(
          ^

TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "..\..\..\..\..\..\config.js" is not a valid package name imported from C:\Users\pro-z\AppData\Roaming\npm\node_modules\gearbox-torrent\server\index.js
    at parsePackageName (node:internal/modules/esm/resolve:782:11)
    at packageResolve (node:internal/modules/esm/resolve:805:5)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:322:34)
    at importModuleDynamically (node:internal/modules/esm/translators:160:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:225:14) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}

Node.js v20.12.0
```

**Comment by Pro-Z-Emil** [comment]
(node:739120) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\pro-z\config.js:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)

Node.js v20.12.0

**Comment by Pro-Z-Emil** [comment]
Using configuration file at C:\Users\pro-z\config.mjs
file:///C:/Users/pro-z/AppData/Roaming/npm/node_modules/gearbox-torrent/server/Requester.js:28
      throw new Error(`HTTP error ${response.status}: ${await response.text()}`)
            ^

Error: HTTP error 401: <h1>401: Unauthorized</h1>
    at request (file:///C:/Users/pro-z/AppData/Roaming/npm/node_modules/gearbox-torrent/server/Requester.js:28:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async reloadAll (file:///C:/Users/pro-z/AppData/Roaming/npm/node_modules/gearbox-torrent/server/connector.js:56:9)
    at async Connector (file:///C:/Users/pro-z/AppData/Roaming/npm/node_modules/gearbox-torrent/server/connector.js:131:3)
    at async Promise.all (index 0)
    at async file:///C:/Users/pro-z/AppData/Roaming/npm/node_modules/gearbox-torrent/server/index.js:56:1

Node.js v20.12.0

**Comment by mikabytes** [comment]
Sounds like the Windows-specific issue is resolved. However, you have found another limitation. We currently only support passwordless communication with Transmission.

Started another Issue https://github.com/mikabytes/gearbox/issues/10 for that.

I'll leave this issue open until we can confirm that Windows works correctly.

**Comment by mikabytes** [comment]
Confirmed, it now runs as expected on Windows. Closing this.
